# Generated by Django 3.2 on 2021-05-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_1', '0002_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
